server:
  port: 2609

spring:
  jpa:
    open-in-view: false

stockholm:
  db:
    file-name: stockholm.db
    read-pool-size: 4
    placeholders:
      id: TEXT
      decimal: TEXT
      instant: TEXT
      date: TEXT
      bool: INTEGER
      json: TEXT
      text: TEXT
      blob: BLOB
